Import("mainEnv", "libEnv")

mainSourceList = Glob("core/*.cpp") + Glob("main/*.cpp")

mainProgram = mainEnv.Program(target="maze_engine", source=mainSourceList)

catch2Object = libEnv.StaticObject(File("test/catch2/catch_amalgamated.cpp"))

testSourceList = Glob("test/*.cpp")

testProgram = mainEnv.Program(target="test/suite", source=[*mainSourceList, *testSourceList, catch2Object])

compilationDatabase = mainEnv.CompilationDatabase()

Return("mainProgram", "testProgram", "compilationDatabase")
