Import("mainEnv", "libEnv")

main_cpp = File("main.cpp")

mainSourceList = Glob("core/*.cpp") + Glob("core/*/*.cpp") + Glob("app/*.cpp") + Glob("app/*/*.cpp")

mainProgram = mainEnv.Program(target="maze_engine", source=[main_cpp] + mainSourceList)

catch2Object = libEnv.StaticObject(File("test/catch2/catch_amalgamated.cpp"))

testSourceList = Glob("test/*.cpp")

testProgram = mainEnv.Program(target="test/suite", source=[*mainSourceList, *testSourceList, catch2Object])

compilationDatabase = mainEnv.CompilationDatabase()

Return("mainProgram", "testProgram", "compilationDatabase")
